repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks  
    rev: v4.4.0  
    hooks:  
      - id: check-added-large-files  
        args: ['--maxkb=500', '--enforce-all']
  
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--settings=pyproject.toml", "--config-root=.", "--resolve-all-configs"]
  
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        files: '^.*(?<!conftest)\.py'
        args:
          - --ignore-missing-imports
          - --no-namespace-packages
          - --python-version=3.9
  
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.2.1'
    hooks:
      - id: ruff
        args: [--fix]
