model_class: TemplateLocalization
num_processes_training: 2
template_localization_config:
  input_encoder:
    mol_out_channels: 1024
    gnn_kwargs:
      hidden_channels: 768
      num_layers: 5
  rewrite_encoder:
    gnn_kwargs:
      hidden_channels: 192
      num_layers: 5
  classification_label_smoothing: 0.0
  free_rewrite_embedding_dim: 32
  classification_min_temperature: 5.0
  classification_max_temperature: 35.0
  num_negative_rewrites_in_localization: 4
  training:
    batch_size: 256
    learning_rate: 0.001
    learning_rate_decay_step_size: 120
    optimizer_betas: [0.9, 0.95]
    n_epochs: 130
    check_val_every_n_epoch: 5
    num_checkpoints_for_averaging: 10
    n_devices: 4
    accumulate_grad_batches: 4
  classification_loss_type: sigmoid
  negative_to_positive_targets_ratio: 30
